JuliaStats/StatsModels.jl

.codecov.yml, README.md, appveyor.yml
I also added a Codecov YAML file to turn off PR comments and added the AppVeyor fast-fail snippet, should we decide to enable AV at some point.
=> Update badges for relocation

src/modelmatrix.jl, test/contrasts.jl
=> Patched the creation of matrix columns from contrast matrix

src/StatsModels.jl, src/modelframe.jl
Necessary to prevent clash with StatsModels
=> qualify coefnames when extending

src/modelframe.jl, test/modelmatrix.jl
...and remove a deprecation warning.
=> Fix small issue in deunionization fix

REQUIRE, src/StatsModels.jl, src/contrasts.jl, src/formula.jl, src/modelframe.jl, src/modelmatrix.jl, src/statsmodel.jl, test/contrasts.jl, test/formula.jl, test/modelmatrix.jl, test/runtests.jl, test/statsmodel.jl
Lots of deprecation warnings still, and some of my fixes are pretty hacky, but tests pass locally.
=> WIP updating for 0.7

src/modelframe.jl, src/statsmodel.jl
msng had a confusing name and a wrong definition in doc. I have renamed the vector and corrected the doc.
=>  msng -> nonmissing

.travis.yml, REQUIRE, src/contrasts.jl, src/modelframe.jl, src/statsmodel.jl, test/runtests.jl
WIP. Starting with running femtocleaner.
=> fixes for 0.7

src/contrasts.jl
minor docs change.
I am reading the docs and trying to relate things to things that I know
=> mention that full-dummy is the same as one-hot in ML literature.

src/schema.jl, test/contrasts.jl, test/modelmatrix.jl
Allows contrasts to be aware of the order (especially important for ordinal features).
=> Bug-fix for respecting levels

Project.toml
=> next release will be version 0.6.0

docs/src/internals.md
- Syntax
- Schema
- Semantics
- Data
=> Document to consider four times for internal transformation

Project.toml
Required to tag
https://github.com/JuliaRegistries/General/pull/1546#issuecomment-505426218
=> add Compat bounds for Julia

Project.toml, src/statsmodel.jl, test/statsmodel.jl
Fixes #125
Patch thanks to @kleinschmidt
=> Fix bug with predict(mm::TableRegressionModel, data; kwargs...)

Project.toml
No changes to code are necessary, this just bumps the version in compat and the
patch version of the package.
=> tables 1 compat

Project.toml
=> add StatsBase 0.33 to compat

src/StatsModels.jl, src/contrasts.jl, src/schema.jl, src/terms.jl, test/contrasts.jl, test/schema.jl
EDIT: I've reverted the Grouping contrasts in favor of putting them in MixedModels.jl for now (see JuliaStats/MixedModels.jl#339).  I've renamed the PR to better reflect the scope of the changes now.
--------------------------
This introduces a new type of "contrasts" which is just a placeholder which
blocks the generation of the contrasts matrix.  This is useful in situations
where you have a variable with a large number of levels which will be used as a
grouping in some 3rd-party defined term.  The main use case I have in mind is
the random effects terms in
[MixedModels.jl](https://github.com/JuliaStats/MixedModels.jl), where the
grouping may have thousands of levels or more.  Because the contrasts matrix is
dense you can easily get an out-of-memory error.
With this PR, you can specify …
=> use DataAPI.levels instead of levels field on contrasts, terms as hints

Project.toml, src/terms.jl, test/modelmatrix.jl
=> Fix bug in interaction of scalar terms for row tables

Project.toml, src/contrasts.jl, test/contrasts.jl
=> enforce that levels are unique for ContrastsMatrix

src/lrtest.jl
changing `categorical` to `string.` fixes issue #250
=> fix docstring for lrtest

src/StatsModels.jl, test/formula.jl, test/traits.jl
=> export `(has|omits)(intercept|response)`

Project.toml, test/runtests.jl
also add stdlib compat entries
=> use TestSetExtensions to show test progress
