.codecov.yml
The syntax in the YAML file was off.
These comments make me crazy.
=> Correctly turn off Codecov comments

docs/src/contrasts.md, docs/src/formula.md, src/StatsModels.jl, src/formula.jl, test/formula.jl, test/modelmatrix.jl, test/statsmodel.jl
Fixes #3 
I've gone with `=>` here since we need something that parses as an infix operator. Once `~` stops being parsed as an infix macro, it's not clear to me whether it will still be parsed as an infix operator at all. Thus I've opted for something we can guarantee is infix.
=> WIP: Replace infix ~ for formulas with a model macro

src/formula.jl
This does a couple of things:
* `tt` is inferred as `Array{Any,1}`, as is `tt .== 1`, so `!(tt .== 1)` fails. Changed to `filter!`.
* Vectorized `|` is deprecated and `.|` doesn't exist in 0.5. Changed to `map`.
=> Update Terms for Julia 0.6 changes

docs/src/formula.md
As mentioned https://github.com/JuliaStats/StatsModels.jl/pull/10#issuecomment-271413898. Thanks to @dmbates for suggesting the correct location in the docs for this.
Note: Not skipping CI since the Travis master build is needed to publish the docs using Documenter.
=> Publish Formula and dropterm documentation

.travis.yml, docs/src/formula.md, docs/src/index.md, src/StatsModels.jl, src/contrasts.jl, src/modelframe.jl, src/modelmatrix.jl, src/statsmodel.jl, test/contrasts.jl, test/formula.jl, test/modelmatrix.jl, test/statsmodel.jl
Move to DataTables temporarily since the code is written to work with Nullable for now. This allows porting https://github.com/JuliaStats/DataFrames.jl/pull/1147/commits/781bbbd0e6724f697fd2dc35867961df548f4434 to StatsModels (first commit), which is a first step towards supporting any kind of categorical input (i.e. both `DataArray` and `CategoricalArray`).
If this works, we could remove the conflicting API from DataTables so that we no longer need the `using` hacks. Then we could start relying only on the AbstractTable interface.
=> Get tests pass again, fix handling of string columns

src/contrasts.jl, src/modelframe.jl, src/modelmatrix.jl
The first commit fixes docs which were not updated by https://github.com/JuliaStats/StatsModels.jl/pull/13.
The second one removes special cases for `CategoricalArray` which are no longer really needed.
=> Remove some uses of CategoricalArrays, update docs

src/formula.jl
!(B::BitArray) is deprecated, use .!(B) instead.
=> Small depreciation fix.

src/contrasts.jl, test/contrasts.jl
Allows ContrastsMatrices to be compared (and used as keys in dicts etc.)
=> hash and equality for ContrastsMatrix types

.travis.yml, REQUIRE, appveyor.yml, docs/src/formula.md, docs/src/index.md, src/StatsModels.jl, src/modelframe.jl, src/modelmatrix.jl, src/statsmodel.jl, test/contrasts.jl, test/formula.jl, test/modelmatrix.jl, test/statsmodel.jl
Keep Nullable in cases where it's used to represent "software engineer's nulls",
i.e. not missing values in data, since the replacement for that in Base is not yet clear.
It should also be possible to avoid returning a `Union{T, Null}` vector from `predict()` when
the input variables are not nullable by storing that in the type information, but
this is left for later.
Also require Julia 0.6.
----------
The two commits should be merged as the first one does not make sense in isolation. Tests won't pass until a new DataFrames release based on `Union{Null, T}` is tagged (tentatively referred to as 0.10 here).
=> Move back to DataFrames and port from Nullable to Missings

src/modelmatrix.jl, test/modelmatrix.jl
I extracted these two simple fixes from #28 and #45 which were more complicated and, to some extent, overridden by #33.  They eliminate warnings from `Pkg.test("StatsModels)` in v0.6.1 of Julia.
=> Fix warnings from `Pkg.test` on v0.6.1

src/modelframe.jl, src/statsmodel.jl, test/statsmodel.jl
I've added the option of manually specifying that a specific model doesn't want the intercept column (application case: Cox model, where the intercept column is meaningless and should be excluded, see discussion in [#2](https://github.com/ararslan/Survival.jl/pull/2) ). This happens with a keyword `intercept = true` to `ModelFrame`. When building a ModelFrame to fit a model from data, this keyword will default to `has_intercept(T)` where `T` is your model type. To add the desired behaviour for your model (in my case CoxModel) you can simply overload it in a specific package. For example, in my case it would be:
```julia
StatsModels.has_intercept(::Type{CoxModel}) = false
```
I know there has been some discussion as to what is the default behaviour for intercept (add it by default or not, …
=> added has_intercept

src/modelframe.jl
Addresses #49 (and possibly JuliaStats/GLM.jl#210).
Before `Missings`, all that was needed to ensure the `model_response` was a standard vector was to convert it to an `Array` (from a `DataArray`).  Now, with missing values potentially represented in a `Array{Union{T,Missing}}`, it's also necessary to use something like `Missings.disallowmissing`.  This won't work with missings in Base (in 0.7), but seeing as we use other features like `Missings.T` elsewhere (like uniqueifying categorical vectors, https://github.com/JuliaStats/StatsModels.jl/blob/d7f285a9f6c8a98943391c9995bd1b3c3614e8a5/src/modelframe.jl#L105-L115) I think it's good enough for now.
The future-proof alternative would be to define those methods here since I don't think they're planned to be supported in Base, or wait until …
=> de-unioninze model_response

src/modelframe.jl
CategoricalArrays 0.3.8 changes `unique` to return values in the order they are encountered, rather than the natural (sorted) order.  This uses `intersect(levels(x), unique(x))` to impose the order of levels on the values returned by `unique`.
=> unique from categoricalarrays 0.3.8

REQUIRE, src/StatsModels.jl, src/deprecated.jl, src/formula.jl, test/contrasts.jl, test/deprecated.jl, test/formula.jl, test/runtests.jl
This PR replaces the spaghetti code that handled the expression re-writes that transform formula surface syntax into a bunch main effects and interactions.  It works by specifying re-write rules (represented by subtypes of `FormulaRewrite`) for associative rule, distributive rule, "star expansion" (`a*b` to `a+b+a&b`), and subtraction (replacing `x-1` with `x + -1`).  These rules are implemented via methods on two functions: `applies(ex::Expr, child_idx::Int, ::Type{T<:FormulaRewrite})` and `rewrite!(ex::Expr, child_idx::Int, ::Type{T<:FormulaRewrite})`.  The first checks whether the child of `ex` at `child_idx` should be re-written under rule `T`, and the second modifies `ex` in place and returns the index of the next child to check.  For example, the associative rule checks whether `ex` …
=> rip out formula parsing and replace it with something sane

src/statsmodel.jl, test/statsmodel.jl
This is a StatsBase API method that was missing.
fixes JuliaStats/GLM.jl#235
=> delegate coefnames for wrapped models to model frame

docs/src/formula.md, src/formula.jl
This will (hopefully) help clear up some confusion around programmatic construction of formulae using `@eval`. (#61, #63, and others)
=> docs for programmatic formula and informative error message for $

src/contrasts.jl, src/formula.jl
The levels of a contrasts struct are `nothing` by default, and are combined with the unique values using `coalesce`. `coalesce(nothing, 1)` on 0.6 returns `1`, but on 0.7 returns `nothing`.  The 0.7 solution is to use `something` instead.
also replace one other occurrence of `coalesce` (in printing LHS of one-sided formula).
fixes #65
=> use something instead of coalesce in contrasts levels

src/statsmodel.jl, test/statsmodel.jl
For models M that specify drop_intercept(M) = true, the fit(M,Formula,df) function adds back and then drops the intercept just before creating the model frame. This same idiom also needs to be applied to predict() otherwise contrast variables are mishandled, resulting in a dimension mismatch error.
This PR:
- fixes predict with drop_intercept model and categorical variables bug
- add tests that used to fail but now pass
=> Fix predict for drop_intercept models

src/statsmodel.jl
Handle prediction that returns a confidence interval
cc @nalimilan
cf https://github.com/JuliaStats/GLM.jl/pull/253
=> predict_confidence

REQUIRE, src/modelframe.jl
The removes a warning which broke the GLM doctests. I plan to make a bugfix release once this is in.
=> Explicitly ask for column names in evalcontrasts when calling eachcol.

src/statsmodel.jl
This reverts commit a64cb50f2e8cfc0e8718fd7651458cd15373d934.
As discussed in #77. Once this has been merged, I'll make a new release and should be able to finish the `predict` behavior without any rush. (@nalimilan we already require DataFrames 0.15 which includes the two argument `eachcol` methods, see https://github.com/JuliaData/DataFrames.jl/commit/dcac4bc383231388629f25877e7b1304cffe0632.)
=> Revert "Handle prediction that returns a confidence interval (#77)"

src/statsmodel.jl
As discussed on Slack. Some considerations:
1. I have made it accept both a Matrix or a NamedTuple. That makes it independent of the GLM version. I don't know if that's desirable but it was suggested on the slack.
2. I have made it return a DataFrame for now as that is what it accepts. We can edit for Tables when Terms 2.0 is merged I guess?
3. I have used dispatch on a nonexported helper function rather than testing the types with if statements. Not sure what the style is here.
4. There is no single-argument `predict(mymodel, interval = :confidence)` method. Where should that be added, here or in GLM?
=> accept namedtuples and return a DataFrame

Project.toml, REQUIRE, test/REQUIRE
In preparation for tagging a release, this replaces REQUIRE and test/REQUIRE with Project.toml
=> RIP REQUIRE, hello Project.toml

src/terms.jl
Miraculously, tests pass with just this change.  The reason is that the underlying columns are all `hcat`ed together at the last stage, and for most of the normal cases there's an intercept term (or a non-intercept term), both of which are arrays with eltype Float64.
It might be possible to get away without even copying, just passing the underlying column straight through, as long as we do defensive copy at the very last stage (matrix term seems like a reasonable place to do this).  But that might be overkill.
This doesn't address the possibility that someone might want a model matrix that's not just Float64s.
As a note to self, I think the long-term solution is to create the model matrix in-place, which would require adding `modelcols!` or some such.  That would reduce copies to a …
=> just copy continuous terms in modelcols, don't convert to float64

src/statsmodel.jl
Needed in particular for the new `level` keyword argument documented in the StatsBase API (https://github.com/JuliaStats/StatsBase.jl/pull/406).
=> Support keyword arguments in coeftable(::TableModels)

Project.toml, src/modelframe.jl, test/modelframe.jl, test/runtests.jl
There was a bug (#133) in how terms are enumerated for the purposes of finding
the term index corresponding to each column of the `ModelMatrix`.  This makes
the handling of that more robust by adding an internal `asgn` function.
Note that the returned indexes are different in 0.6+ since the intercept is
included as a term, instead of being given index 0.
Fixes #133
=> Handle MatrixTerm when calculating column-to-term indexes in ModelMatrix

Project.toml, src/terms.jl, test/extension.jl, test/modelmatrix.jl
This fixes #136 (stackoverflow when there's no more specific method than
`modelcols(::Any, ::Any)`).  An alternative would be to just return the
underlying column (which is probably what we'd want if we do something like
#117).  Making it an explicit error for now means that people can't rely on that
behavior until we've made a decision about what we want long-term.
One larger issue that I'm not sure how to address is that there's currently no
sensible fallback for `::AbstractTerm`s that don't have modelcols methods.
There shouldn't be any of those at this point but if there _are_ then they will
produce the same stack overflow as #136.  The problem is that when you add
methods like `modelcols(::AbstractTerm, ::Any)` or `modelcols(::AbstractTerm,
::NamedTuple)` you get ambiguity errors or …
=> Make modelcols(::Term, d) an error

src/schema.jl, src/terms.jl, test/terms.jl
This is necessary to support special terms that return a tuple of other terms.
This would also allow supporting `*` or even R's `^` via normal "special term"
mechanisms.
=> Clean up tuples with sum after apply_schema

src/terms.jl, test/formula.jl, test/terms.jl
This improves support for using `0` on the LHS for a one-sided formula by making
sure that the `hasintercept` and `omitsintercept` traits are detected correctly
when `0` is present on the LHS.  Currently `0` on the LHS triggers the "omits
intercept" trait which blocks the default inclusion of the intercept for
`StatisticalModel` contexts.
This also updates the `hasresponse` detector to treat LHS `0` as no response.
=> Fix intercept detector traits and hasresponse

Project.toml, src/statsmodel.jl, test/statsmodel.jl
DataFrames aren't a dependency anymore.
Fixes https://github.com/JuliaStats/StatsModels.jl/issues/159. Covered by tests at https://github.com/JuliaStats/GLM.jl/pull/335 (we should add tests with a dummy model type at some point).
=> Fix predict with confidence interval

Project.toml, docs/src/contrasts.md, src/StatsModels.jl, src/contrasts.jl, test/contrasts.jl
`ContrastsCoding` is a footgun unless you really know what you're doing.
Hypothesis coding is a more natural way of specifying manual contrasts, since it
directly expresses differences between conditional means of levels in the matrix
(which is the pseudo-inverse of the contrasts matrix).  This PR introduces a
`HypothesisCoding <: AbstractContrasts` which is exported, and un-exports
`ContrastsCoding` (and adds a note in the docs/help text that points to
hypotheses)
=> Implement HypothesisCoding and ~un-export~ deprecate ContrastsCoding

Project.toml, docs/src/temporal_terms.md, src/StatsModels.jl, src/temporal_terms.jl, test/temporal_terms.jl
Came up on slack: this adds methods for `lead` and `lag` that take a term and an optional number of steps and creates the appropriate `LeadLagTerm` object.  So you can do things like
```julia
f = term(:y) ~ lead(term(:x), 3)
```
which is equivalent to 
```julia
f2 = @formula(y ~ lead(x, 3))
```
=> programmatic construction for lead/lag

Project.toml, test/modelmatrix.jl
Keep support for 0.20 since it's very easy.
Add compatibility bounds to ensure this problem doesn't happen again.
=> Fix tests with DataFrames 0.21

Project.toml
No breaking changes have been introduced since 0.6.11 was tagged (just merged 
#162 (new feature: lrtest), #179 (fix tests), and #181 (internal changes to how
contrast levels are accessed, which doesn't affect any existing code that relies
on `.levels` field of `AbstractContrasts`).
=> bump patch version to 0.6.12

Project.toml
We claim to support DataFrames 0.21, but it wasn't actually used since we didn't support CategoricalArrays 0.8.
=> Bump CategoricalArrays to 0.8

Project.toml, docs/src/formula.md, src/terms.jl, test/terms.jl
As discussed on Slack, this makes it easier to create `Term` objects from `DataFrame` columns, as `names(df)` now returns strings.
=> Add string method for `term`

src/schema.jl, test/modelmatrix.jl, test/runtests.jl, test/schema.jl, test/traits.jl
This adds tests for 
* `implicit_intercept` and `drop_intercept` model traits
* `has_schema`
And fixes at least one bug that turned up in the process (a missing method for
`has_schema(::MatrixTerm)`).
=> Add tests to improve coverage

README.md
Only change is to badge at this point; migration is done on the Travis end
already.
=> Switch integration to travis-ci.com

.github/workflows/TagBot.yml
To avoid disabled workflows after 60 days of inactivity, and to get instant
tagging with merged registrator PRs.  Based on [discourse
post](https://discourse.julialang.org/t/ann-required-updates-to-tagbot-yml/49249).
=> use trigger to run tagbot instead of cron

Project.toml, src/terms.jl, test/terms.jl
Fills in some missing methods for adding collections of terms with `+`, and
tests which target those (formerly) missing methods.
Fixes JuliaStats/MixedModels.jl#452
=> fix missing methods for +

src/terms.jl, test/terms.jl
Fixes #204 by adding a method to check equality of function terms based only on
the type of the original function and the expression (not the generated
anonymous function, which will be different even for identical expressions from
identical environments).
=> Equality of FunctionTerms

docs/src/api.md
It would probably deserve a longer mention elsewhere, but listing it in the API is better than nothing.
=> Add lrtest to manual

Project.toml, src/statsmodel.jl
This delegates to the inner model for return value consistency -- `modelmatrix(::RegressionModel)` is defined in StatsBase and `TableRegressionModel` wraps `RegressionModel`. Users who want the fancy `ModelMatrix` and are specified on `TableRegressionModel` can access that field directly.
Sorry about the whitespace changes.
=> add modelmatrix method for TableRegressionModel

Project.toml, src/terms.jl, test/terms.jl
Fixes #213
The type aliases for tuples of terms used `NTuple` which included empty
tuples.  This changes those aliases to use `Tuple{T, Vararg{T}}` instead, which
enforces that there's at least one `T` (`AbstractTerm` etc.) in the tuple.
=> Fix empty tuple piracy

src/contrasts.jl, test/contrasts.jl
`SeqDiffCoding` has an un-used base kwarg and field.  This can cause confusion (#237 ), so I propose deprecating and eventually removing the kwarg.  This PR removes the internal field and adds a deprecation warning.
=> Deprecate un-used `base=` kwarg for `SeqDiffCoding`

.github/workflows/ci.yml, Project.toml, src/statsmodel.jl, test/statsmodel.jl
I think this is the result of some of the re-organization going on with StatsBase/StatsAPI.
Bottom line is that `coeftable` used to have a default method with `error`, but this is now missing and so we get a `MethodError`.
=> Fix missing `coeftable` method detection.

.github/workflows/ci.yml, Project.toml, src/contrasts.jl, test/contrasts.jl
To maintain compat with Julia 1.0, I had to write the tests using CSV to round trip some strings...that should produce `StringN` types for versions where that's possible and do something reasonable otherwise.
fixes #236
=> relax some checks on eltypes for contrasts and add tests

src/lrtest.jl, test/statsmodel.jl
`lrtest` relied on the deviance rather than the log-likelihood, which is not correct for model families where a dispersion parameter needs to be taken into account. Scaling the deviance would be more efficient than computing the log-likelihood via `loglikelihood`, but there is currently no generic API for this and this may not work for non-GLM models.
We could imagine defining a `likelihoodratio(m1, m2) = loglikelihood(m1) - loglikelihood(m2)` method that packages could override for performance, but this may not be worth it.
Also make the check that more complex models have a strictly better fit than simpler nested ones less strict. The more complex model may have the same deviance, and due to approximations it may even have a slightly higher deviance.
Fixes …
=> Fix `lrtest` for model families with dispersion

src/modelframe.jl, src/schema.jl
* Make `missings_omit()` faster when there are no missing values (use `:` for indexing to speed up `copyto!()`)
* Speed up `concrete_terms()` by avoiding potential and actual levels intersection if their lengths are equal
I have come across these cases while profiling simple `GLM.jl` model that was applied to thousands of small dataframes. About 80% of the time it spent in preparing the model matrix. With these tweaks this overhead was significantly reduced.
=> Faster Corner Cases

src/terms.jl, test/terms.jl
Right now `hasintercept` uses `terms` to get a list of all terms in a formula RHS to check for an intercept term there.  That's not appropriate because it recurses into `FunctionTerm`s which now can include `ConstantTerm(1)` and hence triggers the "has intercept" test.
=> fix bug in `hasintercept`

NEWS.md
I think I got the main things from #183.  Main thing here is to call out run-time function terms and the "standard" upgrade path for package developers using special syntax.
=> update NEWS.md for #183

src/schema.jl, test/contrasts.jl, test/formula.jl
It seems that nightly changes the behavior of `@test_broken` to error if the returned value is not a boolean or no error is thrown.  We had three tests with behavior like this: two where the behavior of `drop_term` changed from previous (pre 0.6) version to not check whether the term was present at all (seems fine and no one has complained about it in 4 years so it's okay to change the semantics), and another where a fix to one issue caused a previously erroring path to no longer error.  I restored the error with a specific method to catch the footgun of passing `:x => DummyCoding` (instead of `:x => DummyCoding()`) earlier.
This doesn't need to block 0.7 release.
=> fix tests on nightly

.github/workflows/docs.yml, docs/src/formula.md, docs/src/internals.md
Ultimately we want to remove GLM-based things from the docs since it means we can't build docs with GLM-breaking changes, but for now this will allow docs to build.
=> use released GLM in docs now

Project.toml, src/terms.jl, test/terms.jl
This was an oversight in #183, fixes #286
=> fix `degree` for `ConstantTerm`/`InterceptTerm`

src/statsmodel.jl, test/statsmodel.jl
It ends up being passed as a positional argument but it should be passed as a keyword argument, see https://github.com/JuliaStats/StatsAPI.jl/blob/20b38e1f73d70fe528097f2f23d662e8830e14ad/src/statisticalmodel.jl#L23, and that is also how GLM defines `coeftable`.
=> Fix coeftable when passing level keyword argument

docs/src/contrasts.md, src/contrasts.jl, src/formula.jl
=> changed Formula to FormulaTerm in documentation and docstrings, fixes #321

src/contrasts.jl
Replaced \times with × that will work in both docstring and docs.
=> Fix issue with \times in docstring

src/contrasts.jl
Since `levels(::CategoricalArray)` now returns a `CategoricalArray`, we need to
unwrap the result before storing it as an `Array` field. This also works
on CategoricalArrays 0.10.
=> Bump CategoricalArrays to 1

.gitignore, Project.toml, src/contrasts.jl, test/contrasts.jl
=> fix boolean-as-categorical support
